// Code generated by entc, DO NOT EDIT.

package order

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the order type in the database.
	Label = "order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldOrderTotal holds the string denoting the order_total field in the database.
	FieldOrderTotal = "order_total"
	// FieldOrderPlaced holds the string denoting the order_placed field in the database.
	FieldOrderPlaced = "order_placed"
	// FieldOrderPaid holds the string denoting the order_paid field in the database.
	FieldOrderPaid = "order_paid"
	// Table holds the table name of the order in the database.
	Table = "orders"
)

// Columns holds all SQL columns for order fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldOrderTotal,
	FieldOrderPlaced,
	FieldOrderPaid,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultOrderPlaced holds the default value on creation for the "order_placed" field.
	DefaultOrderPlaced func() time.Time
	// UpdateDefaultOrderPlaced holds the default value on update for the "order_placed" field.
	UpdateDefaultOrderPlaced func() time.Time
	// DefaultOrderPaid holds the default value on creation for the "order_paid" field.
	DefaultOrderPaid bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
